In [ ]:
#How to manually install numpy?

#!pip install numpy

import numpy as np

np.version.version


In [7]:
sales=[4534,34667,5555,2345]
profit=[234,345,456,223]
profit_ratio=[]
for i in range(0,len(sales)):
    profit_ratio.append(profit[i]/sales[i])
print(profit_ratio)

[0.05161005734450816, 0.009951827386275132, 0.0820882088208821, 0.09509594882729211]


In [ ]:
sales_array=np.array(sales)

In [ ]:
profit_array=np.array(profit)

In [11]:
profit_array/sales_array

array([0.05161006, 0.00995183, 0.08208821, 0.09509595])

In [44]:
list1 = ['A',43,55]
list2 = [43,55,3.8]
list4 = [3.5,55]
list5 = [1,0]

In [9]:
type(list1[0])

str

In [10]:
import numpy as np

n1=np.array(list1)
n2=np.array(list2)
n4=np.array(list4)
n5=np.array(list5)

NameError: name 'list1' is not defined

In [15]:
type(n1[0])

numpy.str_

In [16]:
type(n1[1])

numpy.str_

In [30]:
type(n2[2])

numpy.float64

In [34]:
type(n4[1])

numpy.float64

In [33]:
type(n2[2])

numpy.float64

In [46]:
type(n5[0])

numpy.int32

In [53]:
list3=[1]

In [57]:
n1=np.array(list3)

In [58]:
type(n1[0])

numpy.bool_

In [66]:
#performance wise

import time
size= 100000
l1= range(size)
l2= range(size)
a1=np.arange(size)
a2=np.arange(size)
start=time.time()
result=[(x,y) for x, y in zip(l1,l2)]
print('Time Taken by list')
print((time.time()-start)*1000)

print('\n')
      
start=time.time()
result=a1+a2
print('Time Taken by Array')
print((time.time()-start)*1000)





Time Taken by list
152.46987342834473


Time Taken by Array
22.962570190429688


In [21]:
sales_us=[2343,3455,4567,8765]
sales_jp=[2443,3755,6567,7765]
sales_in=[7343,2455,4567,9765]

In [22]:
sales_matrix=np.array([sales_us,sales_jp,sales_in])

In [23]:
sales_matrix

array([[2343, 3455, 4567, 8765],
       [2443, 3755, 6567, 7765],
       [7343, 2455, 4567, 9765]])

In [18]:
profit_us=[234,355,467,876]
profit_jp=[243,375,667,765]
profit_in=[743,245,457,965]

In [17]:
profit_matrix=np.array([profit_us,profit_jp,profit_in])

In [16]:
profit_matrix

array([[234, 355, 467, 876],
       [243, 375, 667, 765],
       [743, 245, 457, 965]])

In [34]:
prof=profit_matrix/sales_matrix

In [42]:
prof

array([[0.09987196, 0.10274964, 0.10225531, 0.09994295],
       [0.09946787, 0.09986684, 0.10156845, 0.098519  ],
       [0.1011848 , 0.09979633, 0.10006569, 0.09882232]])

In [25]:
sales_matrix.dtype

dtype('int32')

In [26]:
sales_matrix.ndim

2

In [27]:
sales_matrix.shape

(3, 4)

In [28]:
sales_matrix[1,2]

6567

In [30]:
sales_matrix

array([[2343, 3455, 4567, 8765],
       [2443, 3755, 6567, 7765],
       [7343, 2455, 4567, 9765]])

In [37]:
quarter={'Q1':0,'Q2':1,'Q3':2,'Q4':3}
region={'USA':0,'JP':1,'Ind':2}

In [38]:
prof[region['Ind']][quarter['Q4']]

0.09882232462877624

In [40]:
#prof[quarter['Q4']][region['Ind']]

# not possible bcuz it should b row*col

In [46]:
prof[[0,2]]

array([[0.09987196, 0.10274964, 0.10225531, 0.09994295],
       [0.1011848 , 0.09979633, 0.10006569, 0.09882232]])

In [43]:
prof

array([[0.09987196, 0.10274964, 0.10225531, 0.09994295],
       [0.09946787, 0.09986684, 0.10156845, 0.098519  ],
       [0.1011848 , 0.09979633, 0.10006569, 0.09882232]])

In [47]:
prof[[0,2],[0,3]]

array([0.09987196, 0.09882232])

In [48]:
a=np.arange(0,20)

In [49]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [51]:
np.reshape(a,(4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
np.reshape(a,(4,5),'F')

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [53]:
np.cumsum([1,2,3,4,5])

array([ 1,  3,  6, 10, 15], dtype=int32)

In [54]:
np.amax([1,2,3,4,5])

5

In [55]:
np.median([1,2,3,4,5])

3.0

In [56]:
np.median([1,2,3,4,5,6])

3.5

In [57]:
np.std([1,2,3,4,5])

1.4142135623730951

In [58]:
a=np.array([[4.0,5.0,6.0],[8.0,4.0,3.0]])

In [74]:
a

array([[4., 5., 6.],
       [8., 4., 3.]])

In [68]:
b=np.array([2,3,7])

In [70]:
b

array([2, 3, 7])

In [71]:
b.ndim

1

In [72]:
b.dtype

dtype('int32')

In [73]:
a.dtype

dtype('float64')

In [76]:
#get size


a.itemsize

8

In [80]:
#get total size
a.itemsize*a.size
#or
a.nbytes

48

# Accessing/Changing specific elements, rows, columns, etc

In [82]:
# Accessing and changing specific elements in array

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [83]:
# Get a specific element [r, c]
a[1, 5]


13

In [86]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [87]:
# Get a specific col 

a[:, 2]

array([ 3, 10])

In [88]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [89]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [93]:
# replacing columns with 20

a[:,2]=[5]
print(a)



[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [97]:
#replacing particular matrix value with 20:

a[1,5] = 20


a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [120]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [122]:
# Get specific element (work outside in)
b[0,1,1]

4

In [123]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [125]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [126]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# initializing diff types of Array

In [127]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [134]:
# All 1s matrix
np.ones((4,2,2), dtype='float32')

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

In [133]:
# All 1s matrix
np.ones((4,2), dtype='int32')

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [135]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [136]:
# Any other number (full_like)
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [137]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.72505112, 0.30018368],
       [0.00743575, 0.79460016],
       [0.43831285, 0.87124129],
       [0.2957699 , 0.13078364]])

In [142]:
# Random decimal numbers
np.random.rand(4,2,4)

array([[[0.81372591, 0.95060633, 0.0024378 , 0.2669113 ],
        [0.33654659, 0.1406042 , 0.61104359, 0.80834821]],

       [[0.18660384, 0.66958791, 0.04692612, 0.7767447 ],
        [0.64089676, 0.19250282, 0.78420876, 0.57761007]],

       [[0.27609539, 0.29511168, 0.54761205, 0.30856896],
        [0.48335576, 0.01673215, 0.13590022, 0.14836376]],

       [[0.84322166, 0.77224557, 0.2945114 , 0.92099935],
        [0.38543974, 0.12114826, 0.12809995, 0.00722236]]])

In [143]:
np.random.random_sample(a.shape)

array([[0.7157858 , 0.92717114, 0.84621693, 0.02550578, 0.10958126,
        0.65247712, 0.43720738],
       [0.71623033, 0.10000931, 0.0931085 , 0.42267135, 0.88750562,
        0.46164335, 0.54159249]])

In [ ]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

In [144]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [145]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [147]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [148]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# copying Array

In [150]:
a=np.array([1,2,3])
b=a
b[0]=100
print(b)

print(a)

[100   2   3]
[100   2   3]


In [151]:
#copying method:

a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(b)

print(a)


[100   2   3]
[1 2 3]


# Mathematics

In [153]:
a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [156]:
a + 2

array([3, 4, 5, 6])

In [177]:
a - 2

array([-1,  0,  1,  2])

In [178]:
a * 2

array([2, 4, 6, 8])

In [179]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [180]:
a % 2

array([1, 0, 1, 0], dtype=int32)

In [181]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [182]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [186]:
# Take the sin n cos
np.cos(a)


array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [185]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Linear Algebra

In [188]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [190]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [189]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# statistics

In [192]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [193]:
np.min(stats)


1

In [194]:
np.min(stats, axis=0)

array([1, 2, 3])

In [199]:
np.min(stats, axis=1)

array([1, 4])

In [202]:
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorganising arrays

In [203]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [204]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [207]:
# Horizontal stacking vectors

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# miscellaeneous

Load Data from file

In [20]:
import numpy as np

filedata = np.genfromtxt('elsey.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

OSError: elsey.txt not found.

# Boolean Masking and advanced indexing

In [13]:
(~((filedata > 50) & (filedata < 100)))

NameError: name 'filedata' is not defined